### ISSUE TITLE
create workspace error

### ISSUE THREAD

**Issue by ax003d** [ricklamers/gridstudio#21]
I use the docker-compose file to run the server on Mac OS
```
version: "2"
services:
  gridstudio:
    image: ricklamers/gridstudio:release
    volumes:
      - /labs/gridstudio/grid-app:/home/source
      - /labs/gridstudio/grid-app/proxy/userdata:/home/userdata
    ports:
      - 38081:8080
```

Login succeeds, but an error pops up when trying to enter or create a workspace.

<img width="1080" alt="1" src="https://user-images.githubusercontent.com/753663/62213142-d89b3600-b3d4-11e9-9b6b-530039054466.png">

Error logs from docker
```
ridstudio_1  | [Spawn] Tried creating processes GoCmd and NodeCmd
gridstudio_1  | 2019/07/31 12:46:50 http: panic serving 172.23.0.1:42072: runtime error: invalid memory address or nil pointer dereference
gridstudio_1  | goroutine 65 [running]:
gridstudio_1  | net/http.(*conn).serve.func1(0xc00007f220)
gridstudio_1  |         /usr/local/go/src/net/http/server.go:1769 +0x139
gridstudio_1  | panic(0x890ee0, 0xe35fa0)
gridstudio_1  |         /usr/local/go/src/runtime/panic.go:522 +0x1b5
gridstudio_1  | main.destructSession(0xc0001186ce, 0x24, 0xc000072e10, 0xc000072e40)
gridstudio_1  |         /home/source/proxy/manager.go:217 +0x128
gridstudio_1  | main.main.func16(0x98bc60, 0xc000146a80, 0xc00027e900)
gridstudio_1  |         /home/source/proxy/manager.go:778 +0xfb
gridstudio_1  | net/http.HandlerFunc.ServeHTTP(0xc00007c460, 0x98bc60, 0xc000146a80, 0xc00027e900)
gridstudio_1  |         /usr/local/go/src/net/http/server.go:1995 +0x44
gridstudio_1  | net/http.(*ServeMux).ServeHTTP(0xe71d60, 0x98bc60, 0xc000146a80, 0xc00027e900)
gridstudio_1  |         /usr/local/go/src/net/http/server.go:2375 +0x1d6
gridstudio_1  | net/http.serverHandler.ServeHTTP(0xc000078d00, 0x98bc60, 0xc000146a80, 0xc00027e900)
gridstudio_1  |         /usr/local/go/src/net/http/server.go:2774 +0xa8
gridstudio_1  | net/http.(*conn).serve(0xc00007f220, 0x98c460, 0xc000054f80)
gridstudio_1  |         /usr/local/go/src/net/http/server.go:1878 +0x851
gridstudio_1  | created by net/http.(*Server).Serve
gridstudio_1  |         /usr/local/go/src/net/http/server.go:2884 +0x2f4
gridstudio_1  | Tried destroying session 3091f371-61ad-44bc-9242-1fce927ca53f, but sessions not in active usersessions.
gridstudio_1  | 0 user sessions active.
```

**Comment by ax003d** [comment]
Got it, have to use the following ports:
```
  gridstudio:
    image: ricklamers/gridstudio:release
    volumes:
      - /Users/ax003d/labs/gridstudio/grid-app:/home/source
      - /Users/ax003d/labs/gridstudio/grid-app/proxy/userdata:/home/userdata
    ports:
      - 8080:8080
      - 4430:4430
```
