### ISSUE TITLE
docker persistant data volume path

### ISSUE THREAD

**Issue by jeremydouglass** [ricklamers/gridstudio#58]
I'd like to stop and restart grid studio and have the user data persist across container updates.

Where does it write its data -- like users and worksheet files?

Is it /home/source/proxy/userdata, or are there multiple locations?

Here is the configuration I'm looking at:

```
version: '3.1'

volumes:
  gridstudio-data:

services:
  gridstudio:
    image: 'ricklamers/gridstudio:release'
      ports:
        - '12345:8080'
      volumes:gridstudio-data:/home/source/proxy/userdata
```
